## Pandas: Turn a row into columns

In [167]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#%matplotlib inline #so plots are in the notebook

In [175]:
df = pd.read_csv('DOW_MONTHLY.csv')
df.head()

,PERMNO,date,COMNAM,SECSTAT,PERMCO,PRC,RET,SHROUT,vwretd
0,14593,19801128,NaN,NaN,7,NaN,NaN,NaN,0.104952
1,14593,19801231,APPLE COMPUTER INC,R,7,-34.1875,C,55136.0,-0.034411
2,14593,19810130,APPLE COMPUTER INC,R,7,-28.3750,-0.170018,55136.0,-0.040085
3,14593,19810227,APPLE COMPUTER INC,R,7,-26.6250,-0.061674,55136.0,0.015519
4,14593,19810331,APPLE COMPUTER INC,R,7,-24.6250,-0.075117,55136.0,0.046183

In [176]:
df['date'] = pd.to_datetime(df['date'], format='%Y%m%d')
df

,PERMNO,date,COMNAM,SECSTAT,PERMCO,PRC,RET,SHROUT,vwretd
0,14593,1980-11-28,NaN,NaN,7,NaN,NaN,NaN,0.104952
1,14593,1980-12-31,APPLE COMPUTER INC,R,7,-34.1875,C,55136.0,-0.034411
2,14593,1981-01-30,APPLE COMPUTER INC,R,7,-28.3750,-0.170018,55136.0,-0.040085
3,14593,1981-02-27,APPLE COMPUTER INC,R,7,-26.6250,-0.061674,55136.0,0.015519
4,14593,1981-03-31,APPLE COMPUTER INC,R,7,-24.6250,-0.075117,55136.0,0.046183
...,...,...,...,...,...,...,...,...,...
44474,18428,2020-08-31,DOW INC,R,56668,45.1200,0.115928,741121.0,0.068443
44475,18428,2020-09-30,DOW INC,R,56668,47.0500,0.042775,741121.0,-0.035057
44476,18428,2020-10-30,DOW INC,R,56668,45.4900,-0.033156,741752.0,-0.020178
44477,18428,2020-11-30,DOW INC,R,56668,53.0100,0.180699,741752.0,0.123707
44478,18428,2020-12-31,DOW INC,R,56668,55.5000,0.046972,741752.0,0.045048

In [177]:
df = (df.groupby(['date','COMNAM'])
          .RET
          .first()
          .unstack()
)

print(df)

COMNAM          3M CO ALCOA CORP ALLIED CHEMICAL & DYE CORP  \
date
1925-12-31        NaN        NaN                          C
1926-01-30        NaN        NaN                   0.035088
1926-02-27        NaN        NaN                   0.071581
1926-03-31        NaN        NaN                  -0.084746
1926-04-30        NaN        NaN                   0.033769
...               ...        ...                        ...
2020-08-31   0.093175   0.124615                        NaN
2020-09-30  -0.017421  -0.204514                        NaN
2020-10-30  -0.001373   0.110920                        NaN
2020-11-30   0.089022   0.540248                        NaN
2020-12-31   0.011926   0.158291                        NaN

COMNAM     ALLIED CHEMICAL CORP ALLIED CORP ALLIED SIGNAL INC  \
date
1925-12-31                  NaN         NaN               NaN
1926-01-30                  NaN         NaN               NaN
1926-02-27                  NaN         NaN               NaN
1926-03-31                  NaN         NaN               NaN
1926-04-30                  NaN         NaN               NaN
...                         ...         ...               ...
2020-08-31                  NaN         NaN               NaN
2020-09-30                  NaN         NaN               NaN
2020-10-30                  NaN         NaN               NaN
2020-11-30                  NaN         NaN               NaN
2020-12-31                  NaN         NaN               NaN

COMNAM     AMERICAN EXPRESS CO AMERICAN INTERNATIONAL GROUP INC  \
date
1925-12-31                   C                              NaN
1926-01-30           -0.026654                              NaN
1926-02-27           -0.040604                              NaN
1926-03-31           -0.124016                              NaN
1926-04-30            0.072893                              NaN
...                        ...                              ...
2020-08-31            0.088620                        -0.093342
2020-09-30           -0.013190                        -0.044269
2020-10-30           -0.085586                         0.143843
2020-11-30            0.299759                         0.220705
2020-12-31            0.019563                        -0.006764

COMNAM     AMERICAN NATIONAL CAN GROUP INC  AMGEN INC  ...  \
date                                                   ...
1925-12-31                             NaN        NaN  ...
1926-01-30                             NaN        NaN  ...
1926-02-27                             NaN        NaN  ...
1926-03-31                             NaN        NaN  ...
1926-04-30                             NaN        NaN  ...
...                                    ...        ...  ...
2020-08-31                             NaN   0.041893  ...
2020-09-30                             NaN   0.003316  ...
2020-10-30                             NaN  -0.146443  ...
2020-11-30                             NaN   0.030884  ...
2020-12-31                             NaN   0.035489  ...

COMNAM     VERIZON COMMUNICATIONS INC   VISA INC WAL MART STORES INC  \
date
1925-12-31                        NaN        NaN                 NaN
1926-01-30                        NaN        NaN                 NaN
1926-02-27                        NaN        NaN                 NaN
1926-03-31                        NaN        NaN                 NaN
1926-04-30                        NaN        NaN                 NaN
...                               ...        ...                 ...
2020-08-31                   0.031141   0.114969                 NaN
2020-09-30                   0.003712  -0.056701                 NaN
2020-10-30                  -0.031476  -0.091314                 NaN
2020-11-30                   0.060010   0.159375                 NaN
2020-12-31                  -0.027479   0.039838                 NaN

COMNAM     WALGREEN CO WALGREENS BOOTS ALLIANCE INC WALMART INC  \
date
1925-12-31         NaN                          NaN         NaN
1926-01-30         NaN                          NaN         NaN
1926-02-27         NaN                          NaN         NaN
1926-03-31         NaN                          NaN         NaN
1926-04-30         NaN                          NaN         NaN
...                ...                          ...         ...
2020-08-31         NaN                    -0.054593    0.077203
2020-09-30         NaN                    -0.055234    0.007634
2020-10-30         NaN                    -0.052338   -0.008291
2020-11-30         NaN                     0.130361    0.101189
2020-12-31         NaN                     0.049198   -0.053014

COMNAM     WESTINGHOUSE ELECTRIC & MFG CO WESTINGHOUSE ELECTRIC CORP  \
date
1925-12-31                              C                        NaN
1926-01-30                      -0.013491                        NaN
1926-02-27                      -0.001709                        NaN
1926-03-31                      -0.056507                        NaN
1926-04-30                      -0.011050                        NaN
...                                   ...                        ...
2020-08-31                            NaN                        NaN
2020-09-30                            NaN                        NaN
2020-10-30                            NaN                        NaN
2020-11-30                            NaN                        NaN
2020-12-31                            NaN                        NaN

COMNAM     WOOLWORTH CORP WOOLWORTH F W CO
date
1925-12-31            NaN                C
1926-01-30            NaN        -0.006513
1926-02-27            NaN        -0.065554
1926-03-31            NaN        -0.202320
1926-04-30            NaN        -0.037157
...                   ...              ...
2020-08-31            NaN              NaN
2020-09-30            NaN              NaN
2020-10-30            NaN              NaN
2020-11-30            NaN              NaN
2020-12-31            NaN              NaN

[1141 rows x 126 columns]